### ISSUE TITLE
(kleiner) Bug: htaccess in /assets nicht "Contao-Conform" 

### ISSUE THREAD

**Issue by zonky2** [menatwork-ia/clipboard#10]
Hallo,

ich bekomme im BE für alle Dateien in /assets eine 403 und die Icons werden nicht angezeigt - wird die (bzw. werden die) .htaccess Datei(en) Contao-Conform erstellt, funktioniert alles prima

```
<IfModule !mod_authz_core.c>
  Order allow,deny
  Allow from all
</IfModule>
<IfModule mod_authz_core.c>
  Require all granted
</IfModule>
```

**Comment by bytehead** [comment]
+1

**Comment by BugBuster1701** [comment]
:+1:

**Comment by xantippe** [comment]
in 2.0.3-7 noch vorhanden :-(

**Comment by xantippe** [comment]
in 2.0.3-8 noch vorhanden :-(

**Comment by zonky2** [comment]
gefixt in 2.0.6 https://github.com/menatwork-ia/clipboard/commit/d5addd1871c9a2d1504d96c045a4fa79827957dd#diff-1003027229902e4cc585ad9a86051fff
