### ISSUE TITLE
PHP7 Fehler

### ISSUE THREAD

**Issue by BugBuster1701** [menatwork-ia/clipboard#14]
In dieser Zeile:
https://github.com/menatwork-ia/clipboard/blob/3.x/system/modules/clipboard/classes/ClipboardHelper.php#L73

und 
https://github.com/menatwork-ia/clipboard/blob/3.x/system/modules/clipboard/classes/Clipboard.php#L64

**Comment by garyee** [comment]
PR: #16

**Comment by stefanheimes** [comment]
We add a Hotfix brnach for this PR and we removed the 3.x Branch and move all files from the 3.x branch into the master. So we drop the support for contao 2.11 and smaller.

**Comment by stefanheimes** [comment]
New version is online.

**Comment by davidmaack** [comment]
Can be closed, can´t it?
