### ISSUE TITLE
Update composer.json dependencies to ensure Contao 3.5 or higher

### ISSUE THREAD

**Issue by cliffparnitzky** [menatwork-ia/clipboard#20]
Since Version 2.0.7 clipborad could not be used in Contao 3.4 an lower because `String` was replaced with `StringUtil`.

So, the composer.json has to be updated to ensure installing is only allowed in the correct Contao version.

**Comment by frontendschlampe** [comment]
v2.0.6 is working for <3.5

**Comment by plandolt** [comment]
You should make a release with this change on composer.json. I just ran into that issue because i installed 2.0.7.
