### ISSUE TITLE
update .htaccess at icons

### ISSUE THREAD

**Issue by zonky2** [menatwork-ia/clipboard#21]
https://github.com/menatwork-ia/clipboard/blob/master/system/modules/clipboard/assets/icons/.htaccess
to 

```
<IfModule !mod_authz_core.c>
  # Apache 2.2
  Order allow,deny
  Allow from all
</IfModule>
<IfModule mod_authz_core.c>
  # Apache 2.4
  Require all granted
</IfModule>
```

**Comment by BugBuster1701forks** [comment]
Ist seit 2.0.6 enthalten.

**Comment by zonky2** [comment]
fixed https://github.com/menatwork-ia/clipboard/commit/de347db41ab414460f6b8611ac58f6ac29263767
